### ISSUE TITLE
xinetd adds \r (carriage return)

### ISSUE THREAD

**Issue by madeddie** [Maffsie/openwrt-munin-node#1]
Hi,

On my openwrt install the setup you describe with xinetd doesn't work.
xinetd seems to add (or not correctly convert/strip) the carriage return, causing the case statement to fail.

I added these as first lines in the while statement to filter the \r (and any other added whitespace):

```
    cmd=${cmd%[-[:space:]]}
    mod=${mod%[-[:space:]]}
```

**Comment by Maffsie** [comment]
I've pushed a commit adding your fix, I'll test this more thoroughly over the weekend. Thanks for letting me know! :)
